from configs import CONFIGS

CONFIG_ID = 'resnet18_ssl_aug'

MODEL_NAME = CONFIGS[CONFIG_ID]["MODEL_NAME"]
FEATURES_ONLY = CONFIGS[CONFIG_ID]["FEATURES_ONLY"]
NUM_CLASSES = CONFIGS[CONFIG_ID]["NUM_CLASSES"]
FREEZE_ENCODER = CONFIGS[CONFIG_ID]["FREEZE_ENCODER"]

NUM_EPOCHS = CONFIGS[CONFIG_ID]["NUM_EPOCHS"]
ACCUM_GRAD_BATCHES = CONFIGS[CONFIG_ID]["ACCUM_GRAD_BATCHES"]
USE_AMP = CONFIGS[CONFIG_ID]["USE_AMP"]
USE_GRAD_SCALER = CONFIGS[CONFIG_ID]["USE_GRAD_SCALER"]
EARLY_STOP = CONFIGS[CONFIG_ID]["EARLY_STOP"]
PATIENCE = CONFIGS[CONFIG_ID]["PATIENCE"]
OPTIMIZER = CONFIGS[CONFIG_ID]["OPTIMIZER"]
OPTIMIZER_PARAMS = CONFIGS[CONFIG_ID]["OPTIMIZER_PARAMS"]
SCHEDULER = CONFIGS[CONFIG_ID]["SCHEDULER"]
SCHEDULER_PARAMS = CONFIGS[CONFIG_ID]["SCHEDULER_PARAMS"]
CRITERTION = CONFIGS[CONFIG_ID]["CRITERTION"]

BATCH_SIZE = CONFIGS[CONFIG_ID]["BATCH_SIZE"]
INPUT_SIZE = CONFIGS[CONFIG_ID]["INPUT_SIZE"]
NUM_WORKERS = CONFIGS[CONFIG_ID]["NUM_WORKERS"]
PREPROC = CONFIGS[CONFIG_ID]["PREPROC"]
AUGMENT = CONFIGS[CONFIG_ID]["AUGMENT"]
MODEL_FOLDER = CONFIGS[CONFIG_ID]["MODEL_FOLDER"]

MATMUL_PRECISION = CONFIGS[CONFIG_ID]["MATMUL_PRECISION"]
ACCELERATOR = CONFIGS[CONFIG_ID]["ACCELERATOR"]
CUDNN_BENCHMARK = CONFIGS[CONFIG_ID]["CUDNN_BENCHMARK"]
CUDNN_DETERMINISTIC = CONFIGS[CONFIG_ID]["CUDNN_DETERMINISTIC"]

DATA_DIR = CONFIGS[CONFIG_ID]["DATA_DIR"]
CHECKPOINT_FILE = CONFIGS[CONFIG_ID]["CHECKPOINT_FILE"]

ATF = CONFIGS[CONFIG_ID]["ATF"]